import {
  ActivecheckIcon,
  AdsNotIcon,
  AppoIcon,
  AppointmentIcon,
  AttentionSquareIcon,
  BankLinkIcon,
  CalenderIcon,
  CatalogIncompleteIcon,
  ConfigureOfferIncompleteIcon,
  CreativeIcon,
  CreditCardIcon,
  DashbordIcon,
  DateTimeIcon,
  DigitalIcon,
  GetFeatIcon,
  GetFeaturedIcon,
  MessgeIcon,
  MsgCenterIcon,
  NewClientIcon,
  NextPageIcon,
  NoappointIcon,
  NoEasyShareIcon,
  NoPartnerIcon,
  NoPromoCodeIcon,
  NosaleIcon,
  OnboardingIcon,
  PatnershipIcon,
  PhoneLinkIcon,
  ProductNotAddedIcon,
  PromoCodeIcon,
  ReportIcon,
  ReviewIcon,
  RoundmodeltrainingIcon,
  SaleParcentIcon,
  SalesIcon,
  SalessIcon,
  SearchIcon,
  SelectdragIcon,
  SettingIcon,
  StarIcon,
  TeamIcon,
  TeamsIcon,
  VectorIcon,
  GoodIcon,
  BadIcon,
  ViewIcon,
  ViewReportIcon,
  AddVisitIcon,
  AddFollowUpIcon,
  AssignPartnerIcon,
} from "./Icon";
import { BedIcon } from "lucide-react";

export const navItemsData = [
  { id: 1, name: "Dashboard", icon: <DashbordIcon />, path: "/dashboard" },
  {
    id: 2,
    name: "Planner",
    icon: <CalenderIcon />,
    path: "/saidbar",
  },
  { id: 3, name: "Insights", icon: <SearchIcon />, path: "/insights" },
  { id: 4, name: "Partner", icon: <PatnershipIcon />, path: "/deshbord" },
  { id: 5, name: "sales", icon: <SalessIcon />, path: "/deshbord" },
  { id: 6, name: "Team", icon: <TeamsIcon />, path: "/deshbord" },
  { id: 7, name: "Report", icon: <ReportIcon />, path: "/deshbord" },
  {
    id: 8,
    name: "Training",
    icon: <RoundmodeltrainingIcon />,
    path: "/deshbord",
  },
  { id: 9, name: "setting", icon: <SettingIcon />, path: "/deshbord" },
];
export const statsData = [
  {
    title: "Registered vs Assigned",
    icon: <AppointmentIcon />,
    value: "90 / 270",
    change: "+9",
    percent: "+12%",
  },
  {
    title: "Active  vs Registered",
    icon: <ActivecheckIcon />,
    value: "21 / 90",
    change: "+2",
    percent: "+8%",
  },
  {
    title: "Visits this month",
    icon: <NextPageIcon />,
    value: "50 / 250",
    change: "+2",
    percent: "+8%",
  },
  {
    title: "Sales",
    icon: <SaleParcentIcon />,
    value: "150 / 100",
    change: "+9",
    percent: "+6%",
  },
  {
    title: "Appointment",
    icon: <VectorIcon />,
    value: "75 / 100",
    change: "+9",
    percent: "+2%",
  },
  {
    title: "Needs attention",

    icon: <AttentionSquareIcon />,
    value: "15 / 21",
    change: "+2",
    percent: "+2%",
  },
];
export const initialData = [
  {
    id: 1,
    icon: <OnboardingIcon />,
    title: "Onboarding",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 2,
    icon: <SalesIcon />,
    title: "Sales",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 3,
    icon: <PromoCodeIcon />,
    title: "Promo Code",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 4,
    icon: <DigitalIcon />,
    title: "Digital Ads",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 5,
    icon: <StarIcon />,
    title: "Easy Share",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 6,
    icon: <AppoIcon />,
    title: "Appointment",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 7,
    icon: <MessgeIcon />,
    title: "Campaign Message",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 8,
    icon: <GetFeaturedIcon />,
    title: "Get Featured",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 9,
    icon: <SelectdragIcon />,
    title: "Creative Studio",
    value: 0,
    total: 20,
    change: 20,
  },
  {
    id: 10,
    icon: <ReviewIcon />,
    title: "Review",
    value: 0,
    total: 20,
    change: 0,
  },
];
export const healthData = [
  { id: 1, title: "Catalog & Staff", value: 92, score: 9.2 },
  { id: 2, title: "Offers", value: 75, score: 7.5 },
  { id: 3, title: "Client Engagement", value: 42, score: 4.2 },
  { id: 4, title: "Promote Usage", value: 84, score: 8.4 },
  { id: 5, title: "Venue Setup", value: 25, score: 2.5 },
];

export const chartdata = [
  { month: "Jan", registered: 1500, active: 200 },
  { month: "Feb", registered: 1400, active: 600 },
  { month: "Mar", registered: 1800, active: 400 },
  { month: "Apr", registered: 2300, active: 300 },
  { month: "May", registered: 1900, active: 800 },
  { month: "Jun", registered: 2000, active: 1500 },
  { month: "Jul", registered: 2100, active: 1400 },
  { month: "Aug", registered: 1700, active: 1200 },
  { month: "Sep", registered: 1200, active: 1600 },
  { month: "Oct", registered: 1400, active: 1500 },
  { month: "Nov", registered: 1000, active: 700 },
  { month: "Dec", registered: 900, active: 850 },
];
export const tasksData = [
  {
    id: 1,
    title: "Incomplete Onboarding",
    subtitle: "14 Salons",
    icon: <CreditCardIcon />,
  },
  {
    id: 2,
    title: "Off-Peak hours not set",
    subtitle: "8 Salons",
    icon: <NewClientIcon />,
  },
  {
    id: 3,
    title: "Bank account not linked",
    subtitle: "10 Salons",
    icon: <BankLinkIcon />,
  },
  {
    id: 4,
    title: "No monthly target set",
    subtitle: "11 Salons",
    icon: <PhoneLinkIcon />,
  },
  {
    id: 5,
    title: "Staff not added / incomplete",
    subtitle: "13 Salons",
    icon: <TeamIcon />,
  },
  {
    id: 6,
    title: "Subscription Overdue",
    subtitle: "5 Salons",
    icon: <DateTimeIcon />,
  },
];
export const GrowthtasksData = [
  {
    id: 1,
    title: "No Sale (7days)",
    subtitle: "28 salons",
    icon: <NosaleIcon />,
  },
  {
    id: 2,
    title: "No Easy Share (30 days)",
    subtitle: "28 salons",
    icon: <NoEasyShareIcon />,
  },
  {
    id: 3,
    title: "No Appointment(7 days)",
    subtitle: "17 salons",
    icon: <NoappointIcon />,
  },
  {
    id: 4,
    title: "Creative not used (30 d)",
    subtitle: "17 salons",
    icon: <CreativeIcon />,
  },
  {
    id: 5,
    title: "Catalog Incomplete",
    subtitle: "13 salons",
    icon: <CatalogIncompleteIcon />,
  },
  {
    id: 6,
    title: "Ads not used (60 days)",
    subtitle: "5 Salons",
    icon: <AdsNotIcon />,
  },
  {
    id: 7,
    title: "Configure Offer Incomplete",
    subtitle: "21 Salons",
    icon: <ConfigureOfferIncompleteIcon />,
  },
  {
    id: 8,
    title: "Msg Center not used (30 d)",
    subtitle: "21 Salons",
    icon: <MsgCenterIcon />,
  },
  {
    id: 9,
    title: "No Promo code (60 days )",
    subtitle: "21 salons",
    icon: <NoPromoCodeIcon />,
  },
  {
    id: 10,
    title: "Get Feat. not used (60 days)",
    subtitle: "21 Salons",
    icon: <GetFeatIcon />,
  },
  {
    id: 11,
    title: "Product not added ",
    subtitle: "21 Salons",
    icon: <ProductNotAddedIcon />,
  },
  {
    id: 12,
    title: "Partner not visited (30 days)",
    subtitle: "21 Salons",
    icon: <NoPartnerIcon />,
  },
];
export const insightsData = [
  {
    id: 1,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Chroma Lounge",
    address: "281 Madison Street,SoHo Dis...",
    health: 30,
    issue: [{ val: 2 }, { val: 3 }],
    staff: 10,
    onboarding: <GoodIcon />,
    bankacc: <GoodIcon />,
    monthlytarget: <BadIcon />,
    subscription: "Active",
    lastvisit: "3 days ago",
    nextvisit: "July 10, 2025",
    tcname: "Ayesha Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 2,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Maison Glow",
    address: "Luxe Layers Lounge, 1285",
    health: 12,
    issue: [{ val: 3 }, { val: 1 }],
    staff: 5,
    onboarding: <BadIcon />,
    bankacc: <BadIcon />,
    monthlytarget: <GoodIcon />,
    subscription: "Due",
    lastvisit: "11 days ago",
    nextvisit: "Aug 10, 2025",
    tcname: "Meera Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 2,
    img: "/assets/png/Chroma-Lounge.png",
    name: "The Gilded Comb",
    address: "The Styling Suite, 45 Ke....",
    health: 25,
    issue: [{ val: 3 }, { val: 2 }],
    staff: 3,
    onboarding: <GoodIcon />,
    bankacc: <GoodIcon />,
    monthlytarget: <GoodIcon />,
    subscription: "Expired",
    lastvisit: "6 days ago",
    nextvisit: "july 10, 2025",
    tcname: "Ritika Varma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 4,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Luxe Layers",
    address: "Glow Theory Studio, 722...",
    health: 40,
    issue: [{ val: 2 }, { val: 3 }],
    staff: 6,
    onboarding: <GoodIcon />,
    bankacc: <GoodIcon />,
    monthlytarget: <BadIcon />,
    subscription: "Active",
    lastvisit: "3 days ago",
    nextvisit: "July 10, 2025",
    tcname: "Ayesha Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 5,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Opal & Shine",
    address: "Luxe Layers Lounge, 1285",
    health: 12,
    issue: [{ val: 3 }, { val: 1 }],
    staff: 5,
    onboarding: <BadIcon />,
    bankacc: <BadIcon />,
    monthlytarget: <GoodIcon />,
    subscription: "Due",
    lastvisit: "11 days ago",
    nextvisit: "Aug 10, 2025",
    tcname: "Meera Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 6,
    img: "/assets/png/Chroma-Lounge.png",
    name: "The Hair Bar",
    address: "Blush & Beam Salon, Unit 5..",
    health: 15,
    issue: [{ val: 1 }, { val: 2 }],
    staff: 5,
    onboarding: <BadIcon />,
    bankacc: <BadIcon />,
    monthlytarget: <GoodIcon />,
    subscription: "Expired",
    lastvisit: "6 days ago",
    nextvisit: "july 10, 2025",
    tcname: "Ritika Varma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
];
export const textsData = [
  { label: "Critical : 6 ", color: "text-[#F13737]" },
  { label: "Growth : 4", color: "text-[#F58400]" },
  { label: "Health : 8", color: "!text-[#5d14d1d7]" },
];

export const contactsData = [
  {
    role: "Owner :",
    name: "John Walley",
    number: "23246-93902",
  },
  {
    role: "Manager :",
    name: "Esther Howard",
    number: "78363-47438",
  },
];

export const fermtcData = [
  {
    role: "FE :",
    name: "Aditi Singh",
    number: "32456-39432",
  },
  {
    role: "RM :",
    name: "Rohit Sharma",
    number: "23348-32948",
  },
  {
    role: "TC :",
    name: "Priya Kumari",
    number: "84950-34859",
  },
];
export const issuesData = {
  critical: [
    { title: "Incomplete Onboarding", days: "30 days" },
    { title: "Off-Peak hours not set", days: "15 days" },
    { title: "Missing Bank Account", days: "20 days" },
    { title: "Subscription overdue", days: "10 days" },
  ],
  growth: [
    { title: "Website not optimized", days: "12 days" },
    { title: "Low engagement on campaigns", days: "8 days" },
  ],
};

export const reportsData = [
  {
    type: "Visit on",
    date: "April 10th, 2024",
    score: "30/50",
    remarks:
      "Showed keen interest in CRM and membership features. Demo scheduled.",
  },
  {
    type: "Follow Up on",
    date: "April 10th, 2024",
    reason: "Task from previous visit not completed",
    remarks:
      "Showed keen interest in CRM and membership features. Demo scheduled.",
  },
  {
    type: "Visit on",
    date: " April 10th, 2024",
    score: "30/50",
    remarks:
      "Showed keen interest in CRM and membership features. Demo scheduled.",
  },
];

// helperData.js
export const stepsData = [
  {
    type: "info",
    fields: [
      { label: "Name", value: "Raman" },
      { label: "Address", value: "Delhi" },
      { label: "Email", value: "raman@example.com" },
    ],
  },
  {
    type: "question",
    question: "Bot Question 1: How are you today?",
    placeholder: "Your answer",
  },
  {
    type: "question",
    question: "Bot Question 2: What is your favorite color?",
    placeholder: "Your answer",
  },
];

export const namesData = ["Raman", "manish", "mahesh", "ankit", "Rahul"];
export const nameData = ["Ram", "manish", "rajesh", "ankit", "deepak"];

export const reasonData = [
  "Critical Task",
  "CataLog & Offers",
  "Appointment &  Sales",
  "Promote & Marketing",
  "Techanical Issues",
  "Others",
];
export const menuItemsData = [
  { id: 1, label: "View as partner", icon: <ViewIcon /> },
  { id: 2, label: "View Report", icon: <ViewReportIcon /> },
  { id: 3, label: "Add Visit", icon: <AddVisitIcon /> },
  { id: 4, label: "Add Follow Up", icon: <AddFollowUpIcon /> },
  { id: 5, label: "Add Visit Report", icon: <AddVisitIcon /> },
  { id: 6, label: "Assign Partner", icon: <AssignPartnerIcon /> },
];
