import {
  ActivecheckIcon,
  AdsNotIcon,
  AppoIcon,
  AppointmentIcon,
  AttentionSquareIcon,
  BankLinkIcon,
  CalenderIcon,
  CatalogIncompleteIcon,
  ConfigureOfferIncompleteIcon,
  CreativeIcon,
  CreditCardIcon,
  DashbordIcon,
  DateTimeIcon,
  DigitalIcon,
  GetFeatIcon,
  GetFeaturedIcon,
  MessgeIcon,
  MsgCenterIcon,
  NewClientIcon,
  NextPageIcon,
  NoappointIcon,
  NoEasyShareIcon,
  NoPartnerIcon,
  NoPromoCodeIcon,
  NosaleIcon,
  OnboardingIcon,
  PatnershipIcon,
  PhoneLinkIcon,
  ProductNotAddedIcon,
  PromoCodeIcon,
  ReportIcon,
  ReviewIcon,
  RoundmodeltrainingIcon,
  SaleParcentIcon,
  SalesIcon,
  SalessIcon,
  SearchIcon,
  SelectdragIcon,
  SettingIcon,
  StarIcon,
  TeamIcon,
  TeamsIcon,
  VectorIcon,
  GoodIcon,
  BadIcon,
  ViewIcon,
  ViewReportIcon,
  AddVisitIcon,
  AddFollowUpIcon,
  AssignPartnerIcon,
  LastVisitSummaryIcon,
  SubmitIcon,
  SetupIcon,
  ClientEngagementIcon,
  PromoteUsageIcon,
  OfferIcon,
  CatalogStaffIcon,
  ProfileIcon,
  ManageIcon,
  GroIcon,
  GrowIcon,
  OutcomeIcon,
  PromotoIcon,
  PlusIcon,
  SalonIcon,
  TerritoryDetailsIcon,
  BAProfilesIcon,
  BankdetailsIcon,
  EarningIcon,
  DollerIcon,
  FileIcon,
  Appointment3Icon,
} from "./Icon";
import { BedIcon } from "lucide-react";

export const navItemsData = [
  { id: 1, name: "Dashboard", icon: <DashbordIcon />, path: "/dashboard" },
  {
    id: 2,
    name: "Planner",
    icon: <CalenderIcon />,
    path: "/",
  },
  { id: 3, name: "Insights", icon: <SearchIcon />, path: "/insights" },
  { id: 4, name: "Partner", icon: <PatnershipIcon />, path: "/partner" },
  {
    id: 5,
    name: "Appointment",
    icon: <Appointment3Icon />,
    path: "/appointment",
  },
  { id: 6, name: "sales", icon: <SalessIcon />, path: "/sales" },
  { id: 7, name: "Team", icon: <TeamsIcon />, path: "/team" },
  { id: 8, name: "Report", icon: <ReportIcon />, path: "/report" },
  {
    id: 9,
    name: "Training",
    icon: <RoundmodeltrainingIcon />,
    path: "/training",
  },
  { id: 10, name: "setting", icon: <SettingIcon />, path: "/setting" },
];
export const statsData = [
  {
    title: "Registered vs Assigned",
    icon: <AppointmentIcon />,
    value: "90 / 270",
    change: "+9",
    percent: "+12%",
  },
  {
    title: "Active  vs Registered",
    icon: <ActivecheckIcon />,
    value: "21 / 90",
    change: "+2",
    percent: "+8%",
  },
  {
    title: "Visits this month",
    icon: <NextPageIcon />,
    value: "50 / 250",
    change: "+2",
    percent: "+8%",
  },
  {
    title: "Sales",
    icon: <SaleParcentIcon />,
    value: "150 / 100",
    change: "+9",
    percent: "+6%",
  },
  {
    title: "Appointment",
    icon: <VectorIcon />,
    value: "75 / 100",
    change: "+9",
    percent: "+2%",
  },
  {
    title: "Needs attention",

    icon: <AttentionSquareIcon />,
    value: "15 / 21",
    change: "+2",
    percent: "+2%",
  },
];
export const initialData = [
  {
    id: 1,
    icon: <OnboardingIcon />,
    title: "Onboarding",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 2,
    icon: <SalesIcon />,
    title: "Sales",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 3,
    icon: <PromoCodeIcon />,
    title: "Promo Code",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 4,
    icon: <DigitalIcon />,
    title: "Digital Ads",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 5,
    icon: <StarIcon />,
    title: "Easy Share",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 6,
    icon: <AppoIcon />,
    title: "Appointment",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 7,
    icon: <MessgeIcon />,
    title: "Campaign Message",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 8,
    icon: <GetFeaturedIcon />,
    title: "Get Featured",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 9,
    icon: <SelectdragIcon />,
    title: "Creative Studio",
    value: 0,
    total: 20,
    change: 20,
  },
  {
    id: 10,
    icon: <ReviewIcon />,
    title: "Review",
    value: 0,
    total: 20,
    change: 0,
  },
];
export const healthData = [
  { id: 1, title: "Catalog & Staff", value: 92, score: 9.2 },
  { id: 2, title: "Offers", value: 75, score: 7.5 },
  { id: 3, title: "Client Engagement", value: 42, score: 4.2 },
  { id: 4, title: "Promote Usage", value: 84, score: 8.4 },
  { id: 5, title: "Venue Setup", value: 25, score: 2.5 },
];

export const chartdata = [
  { month: "Jan", registered: 1500, active: 200 },
  { month: "Feb", registered: 1400, active: 600 },
  { month: "Mar", registered: 1800, active: 400 },
  { month: "Apr", registered: 2300, active: 300 },
  { month: "May", registered: 1900, active: 800 },
  { month: "Jun", registered: 2000, active: 1500 },
  { month: "Jul", registered: 2100, active: 1400 },
  { month: "Aug", registered: 1700, active: 1200 },
  { month: "Sep", registered: 1200, active: 1600 },
  { month: "Oct", registered: 1400, active: 1500 },
  { month: "Nov", registered: 1000, active: 700 },
  { month: "Dec", registered: 900, active: 850 },
];
export const tasksData = [
  {
    id: 1,
    title: "Incomplete Onboarding",
    subtitle: "14 Salons",
    icon: <CreditCardIcon />,
  },
  {
    id: 2,
    title: "Off-Peak hours not set",
    subtitle: "8 Salons",
    icon: <NewClientIcon />,
  },
  {
    id: 3,
    title: "Bank account not linked",
    subtitle: "10 Salons",
    icon: <BankLinkIcon />,
  },
  {
    id: 4,
    title: "No monthly target set",
    subtitle: "11 Salons",
    icon: <PhoneLinkIcon />,
  },
  {
    id: 5,
    title: "Staff not added / incomplete",
    subtitle: "13 Salons",
    icon: <TeamIcon />,
  },
  {
    id: 6,
    title: "Subscription Overdue",
    subtitle: "5 Salons",
    icon: <DateTimeIcon />,
  },
];
export const GrowthtasksData = [
  {
    id: 1,
    title: "No Sale (7days)",
    subtitle: "28 salons",
    icon: <NosaleIcon />,
  },
  {
    id: 2,
    title: "No Easy Share (30 days)",
    subtitle: "28 salons",
    icon: <NoEasyShareIcon />,
  },
  {
    id: 3,
    title: "No Appointment(7 days)",
    subtitle: "17 salons",
    icon: <NoappointIcon />,
  },
  {
    id: 4,
    title: "Creative not used (30 d)",
    subtitle: "17 salons",
    icon: <CreativeIcon />,
  },
  {
    id: 5,
    title: "Catalog Incomplete",
    subtitle: "13 salons",
    icon: <CatalogIncompleteIcon />,
  },
  {
    id: 6,
    title: "Ads not used (60 days)",
    subtitle: "5 Salons",
    icon: <AdsNotIcon />,
  },
  {
    id: 7,
    title: "Configure Offer Incomplete",
    subtitle: "21 Salons",
    icon: <ConfigureOfferIncompleteIcon />,
  },
  {
    id: 8,
    title: "Msg Center not used (30 d)",
    subtitle: "21 Salons",
    icon: <MsgCenterIcon />,
  },
  {
    id: 9,
    title: "No Promo code (60 days )",
    subtitle: "21 salons",
    icon: <NoPromoCodeIcon />,
  },
  {
    id: 10,
    title: "Get Feat. not used (60 days)",
    subtitle: "21 Salons",
    icon: <GetFeatIcon />,
  },
  {
    id: 11,
    title: "Product not added ",
    subtitle: "21 Salons",
    icon: <ProductNotAddedIcon />,
  },
  {
    id: 12,
    title: "Partner not visited (30 days)",
    subtitle: "21 Salons",
    icon: <NoPartnerIcon />,
  },
];
export const CriticalTaskData = [
  {
    id: 1,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Chroma Lounge",
    address: "281 Madison Street,SoHo Dis...",
    health: 30,
    issue: [{ val: 2 }, { val: 3 }],
    staff: 10,
    onboarding: <GoodIcon />,
    bankacc: <GoodIcon />,
    monthlytarget: <BadIcon />,
    subscription: "Active",
    lastvisit: "3 days ago",
    nextvisit: "July 10, 2025",
    tcname: "Ayesha Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 2,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Maison Glow",
    address: "Luxe Layers Lounge, 1285",
    health: 12,
    issue: [{ val: 3 }, { val: 1 }],
    staff: 5,
    onboarding: <BadIcon />,
    bankacc: <BadIcon />,
    monthlytarget: <GoodIcon />,
    subscription: "Due",
    lastvisit: "11 days ago",
    nextvisit: "Aug 10, 2025",
    tcname: "Meera Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 2,
    img: "/assets/png/Chroma-Lounge.png",
    name: "The Gilded Comb",
    address: "The Styling Suite, 45 Ke....",
    health: 25,
    issue: [{ val: 3 }, { val: 2 }],
    staff: 3,
    onboarding: <GoodIcon />,
    bankacc: <GoodIcon />,
    monthlytarget: <GoodIcon />,
    subscription: "Expired",
    lastvisit: "6 days ago",
    nextvisit: "july 10, 2025",
    tcname: "Ritika Varma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 4,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Luxe Layers",
    address: "Glow Theory Studio, 722...",
    health: 40,
    issue: [{ val: 2 }, { val: 3 }],
    staff: 6,
    onboarding: <GoodIcon />,
    bankacc: <GoodIcon />,
    monthlytarget: <BadIcon />,
    subscription: "Active",
    lastvisit: "3 days ago",
    nextvisit: "July 10, 2025",
    tcname: "Ayesha Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 5,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Opal & Shine",
    address: "Luxe Layers Lounge, 1285",
    health: 12,
    issue: [{ val: 3 }, { val: 1 }],
    staff: 5,
    onboarding: <BadIcon />,
    bankacc: <BadIcon />,
    monthlytarget: <GoodIcon />,
    subscription: "Due",
    lastvisit: "11 days ago",
    nextvisit: "Aug 10, 2025",
    tcname: "Meera Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 6,
    img: "/assets/png/Chroma-Lounge.png",
    name: "The Hair Bar",
    address: "Blush & Beam Salon, Unit 5..",
    health: 15,
    issue: [{ val: 1 }, { val: 2 }],
    staff: 5,
    onboarding: <BadIcon />,
    bankacc: <BadIcon />,
    monthlytarget: <GoodIcon />,
    subscription: "Expired",
    lastvisit: "6 days ago",
    nextvisit: "july 10, 2025",
    tcname: "Ritika Varma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
];
export const ManageData = [
  { label: "Manage: 3", color: "!text-[#F13737]" },
  { label: "Grow: 2", color: "!text-[#F58400]" },
  { label: "Promote: 4", color: "!text-[#5B14D1]" },
  { label: "Overall: 2", color: "!text-[#31A553]" },
];
export const textsData = [
  { label: "Critical : 6 ", color: "!text-[#F13737]" },
  { label: "Growth : 4", color: "text-green-400" },
  { label: "Health : 8", color: "!text-[#5d14d1d7]" },
];

export const contactsData = [
  {
    role: "Owner :",
    name: "John Walley",
    number: "23246-93902",
  },
  {
    role: "Manager :",
    name: "Esther Howard",
    number: "78363-47438",
  },
];

export const fermtcData = [
  {
    role: "FE :",
    name: "Aditi Singh",
    number: "32456-39432",
  },
  {
    role: "RM :",
    name: "Rohit Sharma",
    number: "23348-32948",
  },
  {
    role: "TC :",
    name: "Priya Kumari",
    number: "84950-34859",
  },
];
export const issuesData = {
  critical: [
    { title: "Incomplete Onboarding", days: "30 days" },
    { title: "Off-Peak hours not set", days: "15 days" },
    { title: "Missing Bank Account", days: "20 days" },
    { title: "Subscription overdue", days: "10 days" },
  ],
  growth: [
    { title: "Website not optimized", days: "12 days" },
    { title: "Low engagement on campaigns", days: "8 days" },
  ],
};
export const issues1Data = {
  manage: [
    { title: "Appointment Management", days: "2/5" },
    { title: "Catalog Management", days: "3/5" },
    { title: "Client Management", days: "4/5" },
    { title: "Staff Management", days: "1/5" },
  ],
  growth: [
    { title: "Client Management", days: "4/5" },
    { title: "Staff Management", days: "1/5" },
    { title: "Appointment Management", days: "2/5" },
    { title: "Catalog Management", days: "3/5" },
  ],
  promote: [
    { title: "Staff Management", days: "1/5" },
    { title: "Appointment Management", days: "2/5" },
    { title: "Catalog Management", days: "3/5" },
    { title: "Client Management", days: "4/5" },
  ],
};
export const reportsData = [
  {
    type: "Visit on",
    date: "April 10th, 2024",
    score: "30/50",
    remarks:
      "Showed keen interest in CRM and membership features. Demo scheduled.",
  },
  {
    type: "Follow Up on",
    date: "April 10th, 2024",
    reason: "Task from previous visit not completed",
    remarks:
      "Showed keen interest in CRM and membership features. Demo scheduled.",
  },
  {
    type: "Visit on",
    date: " April 10th, 2024",
    score: "30/50",
    remarks:
      "Showed keen interest in CRM and membership features. Demo scheduled.",
  },
];

// helperData.js
export const stepsData = [
  {
    type: "info",
    fields: [
      { label: "Name", value: "Raman" },
      { label: "Address", value: "Delhi" },
      { label: "Email", value: "raman@example.com" },
    ],
  },
  {
    type: "question",
    question: "Bot Question 1: How are you today?",
    placeholder: "Your answer",
  },
  {
    type: "question",
    question: "Bot Question 2: What is your favorite color?",
    placeholder: "Your answer",
  },
];

export const namesData = [
  "Sanya Desai",
  "Tanya Sethi",
  "Priya Nair",
  "Meera Sharma",
  "Ishita Bose",
];
export const nameData = [
  "Neha Reddy",
  "Neha Singh",
  "Tanya Sethi",
  "Sanya Desai",
];
export const nametcData = [
  "Sanya Desai",
  "Neha Singh",
  "Kavita Menon",
  "Ritika Verma",
  "Meera Sharma",
];
export const namemrData = [
  "Divya Malhotra",
  "manish Vrema",
  "Rhea Malhotra",
  "Neha Singh",
];
export const namemrfeData = [
  "Ayesha Sharma",
  "Ishita Bose",
  "Rhea Malhotra",
  "Neha Singh",
];

export const reasonData = [
  "Critical Task",
  "CataLog & Offers",
  "Appointment &  Sales",
  "Promote & Marketing",
  "Techanical Issues",
  "Others",
];

export const menuItemstab2Data = [
  {
    id: 1,
    label: "View Report",
    icon: <ViewReportIcon />,
    path: "/insights/NewVisit",
  },
  { id: 2, label: "Add Visit", icon: <AddVisitIcon />, path: "/new-visit" },
  {
    id: 3,
    label: "Add Follow Up",
    icon: <AddFollowUpIcon />,
    path: "/new-visit",
  },
  {
    id: 4,
    label: "Add Visit Report",
    icon: <PlusIcon />,
    path: "/NewVisit",
  },
  {
    id: 5,
    label: "Assign Partner",
    icon: <AssignPartnerIcon />,
    path: "/",
  },
];
export const fromsummitData = [
  { icon: <LastVisitSummaryIcon />, label: "Last Visit Summary" },
  { icon: <CatalogStaffIcon />, label: "Catalog & Staff" },
  { icon: <OfferIcon />, label: "Offers" },
  { icon: <PromoteUsageIcon />, label: "Promote Usage" },
  { icon: <ClientEngagementIcon />, label: "Client Engagement" },
  { icon: <SetupIcon />, label: "Set up" },
  { icon: <SubmitIcon />, label: "Submit" },
];
export const ProfileManageData = [
  { icon: <ProfileIcon />, label: "Profile" },
  { icon: <ManageIcon />, label: "Manage" },
  { icon: <GrowIcon />, label: "Grow" },
  { icon: <PromotoIcon />, label: "Promote" },
  { icon: <OutcomeIcon />, label: "Outcome" },
];

export const data = [
  {
    category: "Venue Setup",
    score: "9/10",
    remarks:
      "All complete, missing cancellation policy. Could add more amenities.",
  },
  {
    category: "Catalog & Staff",
    score: "8/10",
    remarks:
      "Services added, 1 inactive staff still listed. Staff profiles need updating.",
  },
  {
    category: "Offers",
    score: "6/10",
    remarks:
      "Gift card & promo active, no membership setup yet. Explore loyalty programs.",
  },
  {
    category: "Promote Usage",
    score: "5/10",
    remarks:
      "Not yet using Get Featured or Campaign Msg. Easy Share links created but low clicks. ",
  },
];
export const Metricdata = [
  {
    Metric: "Services (Count)",
    last: "50 services",
    Current: "40 services",
  },
  {
    Metric: "Package (Count)",
    last: "10 Packages",
    Current: "14 Packages",
  },
  {
    Metric: "Book-a-Look (Count)",
    last: "5 looks",
    Current: "8 looks",
  },
  {
    Metric: "Product (Count)",
    last: "5 looks",
    Current: "22 Products",
  },
  {
    Metric: "Staff (Count)",
    last: "5 staff",
    Current: "3 staff",
  },
];
export const offerdata = [
  {
    Metric: "Voucher (Count)",
    last: "100 vouchers",
    Current: "90 vouchers",
  },
  {
    Metric: "Membership (Count)",
    last: "2 Plans",
    Current: "4 Plans",
  },
  {
    Metric: "Promo code (Count)",
    last: "50 Codes",
    Current: "70 Codes",
  },
  {
    Metric: "Gift Card (Count)",
    last: "10 Cards",
    Current: "12 Cards",
  },
];

export const PromoteUsagedata = [
  {
    Metric: "Get Featured (No. of Days)",
    last: "7 days",
    Current: "8 days",
  },
  {
    Metric: "Easy Share (No. of Links)",
    last: "7 days",
    Current: "6 days",
  },
  {
    Metric: "Easy Share (Clicks)",
    last: "500 clicks",
    Current: "510 clicks",
  },
  {
    Metric: "Creative St. (No. of Temp.)",
    last: "10 templates",
    Current: "12 templates",
  },
  {
    Metric: "Ad Manager (No. of Days)",
    last: "10 templates",
    Current: "9 templates",
  },
  {
    Metric: "Campaign Msg Sent (Count)",
    last: "1000 msgs",
    Current: "1002 msgs",
  },
];

export const ClientEngagementdata = [
  {
    Metric: "Appointment  Received ",
    last: "150",
    Current: "140",
  },
  {
    Metric: "Appointment  Complete ",
    last: "140",
    Current: "146",
  },
  {
    Metric: "Repeat Clients Visit ",
    last: "80",
    Current: "510",
  },
  {
    Metric: "New Client Add ",
    last: "60",
    Current: "62",
  },
  {
    Metric: "Total Client",
    last: "500",
    Current: "400",
  },
  {
    Metric: "Review Received ",
    last: "20",
    Current: "30",
  },
  {
    Metric: "Review Received ",
    last: "30",
    Current: "40",
  },
  {
    Metric: "Sales",
    last: "₹50,000",
    Current: "₹45,000",
  },
];
export const Setupdata = [
  {
    Metric: "Business Name and Logo",
    last: "Yes",
    Current: "Yes",
  },
  {
    Metric: "Complete Add. and Location Pin Set",
    last: "Yes",
    Current: "No",
  },
  {
    Metric: "About (Description)",
    last: "Yes",
    Current: "Yes",
  },
  {
    Metric: "Off Peak Hours",
    last: "No",
    Current: "Yes",
  },
  {
    Metric: "Contact Number verified",
    last: "Yes",
    Current: "Yes",
  },
  {
    Metric: "Social Media Links",
    last: "Yes",
    Current: "No",
  },
  {
    Metric: "Bank Account",
    last: "No",
    Current: "Yes",
  },
  {
    Metric: "Compliance - Staff  'Curr. Employed'",
    last: "Yes",
    Current: "Yes",
  },
];
export const timesData = [
  "01:00 PM",
  "02:00 PM",
  "03:00 PM",
  "04:00 PM",
  "05:00 PM",
  "06:00 PM",
  "07:00 PM",
  "08:00 PM",
  "09:00 PM",
  "10:00 PM",
  "12:00 PM",
  "01:00 AM",
  "02:00 AM",
  "03:00 AM",
  "04:00 AM",
  "05:00 AM",
  "06:00 AM",
  "07:00 AM",
  "08:00 AM",
  "09:00 AM",
  "10:00 AM",
  "11:00 AM",
  "12:00 AM",
];

export const salonSizesData = [
  { id: "size-1", value: "0-3", label: "0 - 3 seats" },
  { id: "size-2", value: "4-7", label: "4 - 7 seats" },
  { id: "size-3", value: "8-12", label: "8 - 12 seats" },
  { id: "size-4", value: "16+", label: "16 & above" },
];

export const ratingLabelsData = [
  "Rate the following from 1 - 5 ",
  "1 - not needed",
  "2 - not sure",
  "3 - needed but not immediately",
  "4 - needed",
  "5 - strongly needed",
];

export const GrowthTaskData = [
  {
    id: 1,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Chroma Lounge",
    address: "281 Madison Street,SoHo Dis...",
    health: 30,
    issue: [{ val: 2 }, { val: 3 }],
    saleid: "₹12,500",
    Appt: "5",
    Catalog: "20/3",
    Promocode: "0",
    Getfeat: "0",
    EasyShare: "10/2",
    CreativeStudio: "0",
    Admanager: "0",
    CompMsg: "0",
    NextVisit: "July 14,2025",
    tcname: "Ayesha Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
  },
  {
    id: 2,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Maison Glow",
    address: "Luxe Layers Lounge, 1285",
    health: 12,
    issue: [{ val: 3 }, { val: 2 }],
    saleid: "₹15,000",
    Appt: "10",
    Catalog: "20/3",
    Promocode: "2",
    Getfeat: "2",
    EasyShare: "10/4",
    CreativeStudio: "2",
    Admanager: "3",
    CompMsg: "20",
    NextVisit: "Aug 10 ,2025",
    tcname: "Meera Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
  },
  {
    id: 3,
    img: "/assets/png/Chroma-Lounge.png",
    name: "The Gilded Comb",
    address: "The Styling Suite, 45 Ke....",
    health: 25,
    issue: [{ val: 1 }, { val: 3 }],
    saleid: "₹18,750",
    Appt: "6",
    Catalog: "20/3",
    Promocode: "5",
    Getfeat: "4",
    EasyShare: "20/3",
    CreativeStudio: "4",
    Admanager: "5",
    CompMsg: "15",
    NextVisit: "July 14,2025",
    tcname: "Ritika Varma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
  },
  {
    id: 4,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Luxe Layers",
    address: "Blush & Beam Salon, Unit 5...",
    health: 16,
    issue: [{ val: 3 }, { val: 4 }],
    saleid: "₹20,000",
    Appt: "8",
    Catalog: "20/3",
    Promocode: "5",
    Getfeat: "5",
    EasyShare: "12/4",
    CreativeStudio: "6",
    Admanager: "8",
    CompMsg: "12",
    NextVisit: "sep 11,2025",
    tcname: "Tanya Sethi",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
  },
  {
    id: 5,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Opal & Shine",
    address: "Radiance Hair Studio, 3rd f..",
    health: 35,
    issue: [{ val: 4 }, { val: 3 }],
    saleid: "₹23,400",
    Appt: "12",
    Catalog: "20/3",
    Promocode: "5",
    Getfeat: "5",
    EasyShare: "12/4",
    CreativeStudio: "6",
    Admanager: "8",
    CompMsg: "12",
    NextVisit: "July 10,2025",
    tcname: "Kavita Menon",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
  },
];

export const RegisteredPartnerData = [
  {
    id: 1,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Chroma Lounge",
    city: "MG Road, Banglore",
    health: 45,
    issue: [{ val: 2 }, { val: 3 }],
    appt: "150",
    sales: "80",
    tcname: "Amitabh Bachan",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    lastVisit: "July 14,2025",
    nextVisit: "July 5,2025",
  },
  {
    id: 2,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Maison Glow",
    city: "Brigade Road, Bangalore",
    health: 40,
    issue: [{ val: 2 }, { val: 3 }],
    appt: "50",
    sales: "80",
    tcname: "-",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    lastVisit: "July 14,2025",
    nextVisit: "-",
  },
  {
    id: 3,
    img: "/assets/png/Chroma-Lounge.png",
    name: "The Gilded Comb",
    city: "Cloud City",
    health: 35,
    issue: [{ val: 2 }, { val: 3 }],
    appt: "₹120",
    sales: "120",
    tcname: "Ayesha Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    lastVisit: "Jun 01,2025",
    nextVisit: "Apr 10,2025",
  },
  {
    id: 4,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Luxe Layers",
    city: "Treasure Town",
    health: 42,
    issue: [{ val: 2 }, { val: 3 }],
    appt: "₹110",
    sales: "125",
    tcname: "Amitabh Bachan",
    rmname: "-",
    fename: "Vijay Patel",
    lastVisit: "July 14,2025",
    nextVisit: "July 25,2025",
  },
  {
    id: 5,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Opal & Shine",
    city: "Cloud City",
    health: 40,
    issue: [{ val: 2 }, { val: 3 }],
    appt: "₹130",
    sales: "60",
    tcname: "Suresh Mehta",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    lastVisit: "Apr 14,2025",
    nextVisit: "July 5,2025",
  },
];

export const ProspectivePartnerData = [
  {
    id: 1,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Radiance Hair Studio",
    city: "Brigade Road, Bangalore",
    ContactPerson: "John Smith (owner)",
    Phoneno: "23249-39212",
    Size: "0-3",
    Manage: "4.5",
    Grow: "3.0",
    Promote: "3.5",
    OverallInterest: "1/5",
    LastVisit: "July 14 ,2025",
    Followup: "July 19 ,2025",
    Remarks: "Wants to onboard ASAP. F",
    tcname: "Amitabh Bachan",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
  },
  {
    id: 1,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Urban Trendz",
    city: "Linking Road, Mumbai",
    ContactPerson: "Varun Mehta (owner)",
    Phoneno: "91234-56789",
    Size: "4-7",
    Manage: "3.0",
    Grow: "4.0",
    Promote: "3.0",
    OverallInterest: "2/5",
    LastVisit: "July 14 ,2025",
    Followup: "July 19 ,2025",
    Remarks: "Wants to onboard ASAP. F",
    tcname: "Amitabh Bachan",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
  },
  {
    id: 3,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Terra Firma Barbers",
    city: "Rock Town",
    ContactPerson: "Clay Stone (owner)",
    Phoneno: "555-7702",
    Size: "8-12",
    Manage: "-  ",
    Grow: "-",
    Promote: "-",
    OverallInterest: "3/5",
    LastVisit: "July 18 ,2025",
    Followup: "July 18 ,2025",
    Remarks: "Wants to onboard ASAP. F",
    tcname: "-",
    rmname: "-",
    fename: "-",
  },
  {
    id: 4,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Radiance Hair Studio ",
    city: "Brigade Road, Bangalore",
    ContactPerson: "John Smith (owner)",
    Phoneno: "23249-39212",
    Size: "4-7",
    Manage: "4.5",
    Grow: "3.0",
    Promote: "3.5",
    OverallInterest: "4/5",
    LastVisit: "July 14 ,2025",
    Followup: "July 19 ,2025",
    Remarks: "Wants to onboard ASAP. F",
    tcname: "Amitabh Bachan",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
  },
  {
    id: 1,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Urban Trendz",
    city: "Linking Road, Mumbai",
    ContactPerson: "Varun Mehta (owner)",
    Phoneno: "91234-56789",
    Size: "0-3",
    Manage: "3.0  ",
    Grow: "4.0",
    Promote: "3.0",
    OverallInterest: "2/5",
    LastVisit: "July 14 ,2025",
    Followup: "July 19 ,2025",
    Remarks: "Wants to onboard ASAP. F",
    tcname: "Amitabh Bachan",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
  },
];

export const tcnmanberData = [
  {
    image: "/assets/png/aarav-sharma.png",
    name: "Aarav Sharma",
    gender: "Male",
    color: "#31A553",
    role: "TC",
    phone: "+919876500101",
    email: "aarav.sharma@example.com",
    manages: "2 RM & 3 FE",
    totalSalons: "1100",
    roleBorder: "#FFAB47",
    roleBg: "#FFEFDB",
  },
  {
    image: "/assets/png/priya-singh.png",
    name: "Priya Singh",
    gender: "Female",
    color: "#F00",
    role: "TC",
    phone: "+919876500101",
    email: "tanya.hill@example.com",
    manages: "2 RM & 3 FE",
    totalSalons: "1100",
    roleBorder: "#FFAB47",
    roleBg: "#FFEFDB",
  },
];
export const rmnmanberData = [
  {
    image: "/assets/svg/rm1.svg",
    name: "Wade Warren",
    gender: "Male",
    color: "#31A553",
    role: "RM",
    phone: "+919876500101",
    email: "curtis.weaver@example.com",
    manages: "6FE",
    totalSalons: "1100",
    roleBorder: "#8EBAF6",
    roleBg: "#CFE2FC33",
  },
  {
    image: "/assets/svg/rm2.svg",
    name: "Theresa Webb",
    gender: "Female",
    color: "#F00",
    role: "RM",
    phone: "+919876500101",
    email: "kenzi.lawson@example.com",
    manages: "6FE",
    totalSalons: "1100",
    roleBorder: "#8EBAF6",
    roleBg: "#CFE2FC33",
  },
  {
    image: "/assets/svg/rm3.svg",
    name: "Darrell Steward",
    gender: "Female",
    color: "#31A553",
    role: "RM",
    phone: "+919876500101",
    email: "michael.mitc@example.com",
    manages: "6FE",
    totalSalons: "1100",
    roleBorder: "#8EBAF6",
    roleBg: "#CFE2FC33",
  },
  {
    image: "/assets/svg/rm1.svg",
    name: "Kathryn Murphy",
    gender: "Female",
    color: "#F00",
    role: "RM",
    phone: "+919876500101",
    email: "tanya.hill@example.com",
    manages: "6FE",
    totalSalons: "1100",
    roleBorder: "#8EBAF6",
    roleBg: "#CFE2FC33",
  },
];
export const fmnmanberData = [
  {
    image: "/assets/svg/rm1.svg",
    name: "Wade Warren",
    gender: "Male",
    color: "#31A553",
    role: "FM",
    phone: "+919876500101",
    email: "bill.sanders@example.com",
    totalSalons: "1100",
    roleBorder: "#31A553",
    roleBg: "#E3F7E9",
  },
  {
    image: "/assets/svg/rm2.svg",
    name: "Theresa Webb",
    gender: "Female",
    color: "#31A553",
    role: "FM",
    phone: "+919876500101",
    email: "tim.jennings@example.com",
    totalSalons: "1100",
    roleBorder: "#31A553",
    roleBg: "#E3F7E9",
  },
  {
    image: "/assets/svg/rm3.svg",
    name: "Darrell Steward",
    gender: "Female",
    color: "#F00",
    role: "FM",
    phone: "+919876500101",
    email: "debbie.baker@example.com",
    roleBorder: "#31A553",
    roleBg: "#E3F7E9",
    totalSalons: "1100",
  },
  {
    image: "/assets/svg/rm1.svg",
    name: "Kathryn Murphy",
    gender: "Female",
    roleBorder: "#31A553",
    roleBg: "#E3F7E9",
    color: "#31A553",
    role: "FM",
    phone: "+919876500101",
    email: "sara.cruz@example.com",
    totalSalons: "1100",
  },
  {
    image: "/assets/svg/fm1.svg",
    name: "Wade Warren",
    gender: "Male",
    color: "#31A553",
    role: "FM",
    phone: "+919876500101",
    email: "felicia.reid@example.com",
    totalSalons: "1100",
    roleBorder: "#31A553",
    roleBg: "#E3F7E9",
  },
  {
    image: "/assets/svg/fm2.svg",
    name: "Darrell Steward",
    gender: "Male",
    color: "#F00",
    role: "FM",
    phone: "+919876500101",
    email: "bill.sanders@example.com",
    totalSalons: "1100",
    roleBorder: "#31A553",
    roleBg: "#E3F7E9",
  },
  {
    image: "/assets/svg/fm3.svg",
    name: "Jane Cooper",
    gender: "Male",
    color: "#31A553",
    role: "FM",
    phone: "+919876500101",
    email: "jessica.hanson@example.com",
    roleBorder: "#31A553",
    roleBg: "#E3F7E9",
    totalSalons: "1100",
  },
  {
    image: "/assets/svg/fm4.svg",
    name: "Kathryn Murphy",
    gender: "Female",
    color: "#F00",
    role: "FM",
    phone: "+919876500101",
    email: "kenzi.lawson@example.com",
    totalSalons: "1100",
    roleBorder: "#31A553",
    roleBg: "#E3F7E9",
  },
  {
    image: "/assets/svg/fm5.svg",
    name: "Courtney Henry",
    gender: "Male",
    color: "#31A553",
    role: "FM",
    phone: "+919876500101",
    email: "michelle.rivera@example.com",
    totalSalons: "1100",
    roleBorder: "#31A553",
    roleBg: "#E3F7E9",
  },
  {
    image: "/assets/svg/fm6.svg",
    name: "Guy Hawkins",
    gender: "Male",
    color: "#31A553",
    role: "FM",
    phone: "+919876500101",
    email: "kenzi.lawson@example.com",
    totalSalons: "1100",
    roleBorder: "#31A553",
    roleBg: "#E3F7E9",
  },
];

export const currentData = [
  {
    icon: <OnboardingIcon />,
    name: "Onboarding",
    value: 60,
    change: "+34%",
    totel: "12/20",
  },
  {
    icon: <SalesIcon />,
    name: "Sales",
    value: 80,
    change: "+22%",
    totel: "16/20",
  },
  {
    icon: <PromoCodeIcon />,
    name: "Promo Code",
    value: 50,
    change: "+60%",
    totel: "10/20",
  },
  {
    icon: <DigitalIcon />,
    name: "Digital Ads",
    value: 55,
    change: "+6%",
    totel: "11/20",
  },
  {
    icon: <StarIcon />,
    name: "Easy Share",
    value: 45,
    change: "+3%",
    totel: "9/20",
  },
  {
    icon: <AppoIcon />,
    name: "Appointment",
    value: 70,
    change: "+6%",
    totel: "14/20",
  },
  {
    icon: <MessgeIcon />,
    name: "Campaign Message",
    value: 40,
    change: "-5%",
    totel: "8/20",
  },
  {
    icon: <GetFeaturedIcon />,
    name: "Get Featured",
    value: 75,
    change: "+12%",
    totel: "15/20",
  },
  {
    icon: <SelectdragIcon />,
    name: "Creative Studio",
    value: 75,
    change: "+12%",
    totel: "15/20",
  },
  {
    icon: <ReviewIcon />,
    name: "Review",
    value: 45,
    change: "+3%",
    totel: "9/20",
  },
];

export const fieldsData = [
  {
    label: "Onboarding Salons",
    value: "22",
    note: "No. of new salons successfully onboarded",
  },
  {
    label: "Active vs Assigned Salon Ratio",
    value: "90%",
    note: "% of active salons out of total assigned",
  },
  {
    label: "Visit Conducted",
    value: "200",
    note: "Total number of partner visits completed.",
  },
  {
    label: "Appointments Booked",
    value: "94",
    note: "Total online + offline appointments created by assigned salons.",
  },
  {
    label: "Sales Count",
    value: "33",
    note: "Total number of sales transactions by assigned salons.",
  },
  {
    label: "Promo Code Generated",
    value: "43",
    note: "Count of unique promo codes generated in the month.",
  },
  {
    label: "Get Featured",
    value: "41",
    note: "Count of salons actively using the ‘Get Featured’ service.",
  },
  {
    label: "Digital Ads",
    value: "41",
    note: "Count of salons running digital ad campaigns.",
  },
  {
    label: "Creative Studio",
    value: "25",
    note: "Count of salons utilizing the Creative Studio.",
  },
  {
    label: "Easy Share",
    value: "39",
    note: "Count of salons using the Easy Share feature.",
  },
  {
    label: "Campaign Message Sent",
    value: "63",
    note: "Count of campaign messages sent by salons.",
  },
];
export const OverallTeamData = [
  {
    icon: <AppointmentIcon />,
    title: "Team Onboarding Achievement",
    value: "89%",
    text: "Against total team target",
  },
  {
    icon: <BankLinkIcon className={"!w-5 !h-5"} />,
    title: "Avg. Active Salon Ratio",
    value: "53.3%",
    text: "Average across all FEs",
  },
  {
    icon: <TeamIcon className={"!w-5 !h-5"} />,
    title: "Team Visits Achievement",
    value: "83%",
    text: "Against total team target",
  },
  {
    icon: <TeamIcon className={"!w-5 !h-5"} />,
    title: "Sales Count",
    value: "81%",
    text: "Against total team target",
  },
];

export const tcTeamData = [
  { name: "Rohan Mehta", value: 82 },
  { name: "Sneha Reddy", value: 82 },
];
export const rmTeamData = [
  { name: "Rohan Mehta", value: 82 },
  { name: "Sneha Reddy", value: 82 },
  { name: "Vikram Patel", value: 85 },
  { name: "Ananya Gupta", value: 91 },
];
export const fmTeamData = [
  { name: "Rohan Mehta", value: 82 },
  { name: "Sneha Reddy", value: 82 },
  { name: "Vikram Patel", value: 85 },
  { name: "Ananya Gupta", value: 91 },

  { name: "Arjun Kumar", value: 78 },
  { name: "Sneha Reddy", value: 82 },
  { name: "Divya Joshi", value: 84 },
  { name: "Kabir Das", value: 85 },
  { name: "Ravi Sankar", value: 93 },
  { name: "Pooja Desai", value: 94 },
  { name: "Isaan Roy", value: 84 },
];
export const ReportRegisteredData = [
  {
    ids: "VIS-009",
    salonname: "Luxe Locks Studio",
    date: "15/07/2024 ",
    issue: [{ val: 2 }, { val: 3 }],
    offer: 9,
    staff: 5,
    promote: 5,
    client: 6,
    setup: 7,
    status: "Planned",
    remarks: "Interested in collaboration, requested service details.",
  },
  {
    ids: "VISIT-09999",
    salonname: "Divine Glow Stud..",
    date: "18/08/2024 ",
    issue: [{ val: 2 }, { val: 3 }],
    offer: 8,
    staff: 6,
    promote: 6,
    client: 6,
    setup: 5,
    status: "Expired",
    remarks: "Not very responsive follow",
  },
  {
    ids: "SVST-025",
    salonname: "Élan Salon & Spa",
    date: "19/08/2024 ",
    issue: [{ val: 2 }, { val: 3 }],
    offer: 8,
    staff: 7,
    promote: 8,
    client: 8,
    setup: 8,
    status: "Planned",
    remarks: "Wants to onboard ASAP. F",
  },
  {
    ids: "VISIT-09999",
    salonname: "Divine Glow Stud..",
    date: "18/08/2024 ",
    issue: [{ val: 2 }, { val: 3 }],
    offer: 7,
    staff: 8,
    promote: 9,
    client: 5,
    setup: 6,
    status: "Completed",
    remarks: "Highly potential partner,located in a prime area.",
  },
];

export const salonData = [
  {
    image: "/assets/png/salon2.png",
    title: "Da Salon Partner",
    desc: "Learn how to onboard a salon partner with ease. A simple video guide for your team.",
    link: "https://da.salon.partner.com",
    date: "10-03-2024",
    time: "9:15 AM",
    rating: 5,
  },
  {
    image: "/assets/png/salon3.png",
    title: "Da Salon Connect",
    desc: "Connect with partnered salons instantly. View status, updates, and onboarding progress.",
    link: "https://da.salon.connect.com",
    date: "05-03-2024",
    time: "9:15 AM",
    rating: 5,
  },
  {
    image: "/assets/png/salon4.png",
    title: "Da Salon Market",
    desc: "Shop salon essentials, offers & packages. Boost your salon with curated deals.",
    link: "https://da.salon.market.com",
    date: "01-03-2024",
    time: "9:15 AM",
    rating: 5,
  },
  {
    image: "/assets/png/salon5.png",
    title: "Business Associates",
    desc: "Connect and collaborate with trusted associates. Build strong relationships that grow your network.",
    link: "https://business.associates.com",
    date: "25-02-2024",
    time: "9:15 AM",
    rating: 5,
  },
  {
    image: "/assets/png/salon6.png",
    title: "Da Salon Partner",
    desc: "Learn how to onboard a salon partner with ease. A simple video guide for your team.",
    link: "https://da.salon.partner.com",
    date: "10-03-2024",
    time: "9:15 AM",
    rating: 5,
  },
  {
    image: "/assets/png/salon7.png",
    title: "Da Salon Connect",
    desc: "Connect with partnered salons instantly. View status, updates, and onboarding progress.",
    link: "https://da.salon.connect.com",
    date: "05-03-2024",
    time: "9:15 AM",
    rating: 5,
  },
  {
    image: "/assets/png/salon8.png",
    title: "Da Salon Market",
    desc: "Shop salon essentials, offers & packages. Boost your salon with curated deals.",
    link: "https://da.salon.market.com",
    date: "01-03-2024",
    time: "9:15 AM",
    rating: 5,
  },
  {
    image: "/assets/png/salon9.png",
    title: "Business Associates",
    desc: "Connect and collaborate with trusted associates. Build strong relationships that grow your network.",
    link: "https://business.associates.com",
    date: "25-02-2024",
    time: "9:15 AM",
    rating: 5,
  },
  {
    image: "/assets/png/salon10.png",
    title: "Da Salon Partner",
    desc: "Learn how to onboard a salon partner with ease. A simple video guide for your team.",
    link: "https://da.salon.partner.com",
    date: "10-03-2024",
    time: "9:15 AM",
    rating: 5,
  },
  {
    image: "/assets/png/salon11.png",
    title: "Da Salon Connect",
    desc: "Connect with partnered salons instantly. View status, updates, and onboarding progress.",
    link: "https://da.salon.connect.com",
    date: "05-03-2024",
    time: "9:15 AM",
    rating: 5,
  },
  {
    image: "/assets/png/salon12.png",
    title: "Da Salon Market",
    desc: "Shop salon essentials, offers & packages. Boost your salon with curated deals.",
    link: "https://da.salon.market.com",
    date: "01-03-2024",
    time: "9:15 AM",
    rating: 5,
  },
  {
    image: "/assets/png/salon13.png",
    title: "Business Associates",
    desc: "Connect and collaborate with trusted associates. Build strong relationships that grow your network.",
    link: "https://business.associates.com",
    date: "25-02-2024",
    time: "9:15 AM",
    rating: 5,
  },
];

export const prospectiveData = [
  {
    ids: "VIS-009",
    salonname: "Luxe Locks Studio",
    date: "14/07/2024 ",
    seat: "5-7",
    manage: 3,
    grow: 2,
    promote: 1,
    overall: 3,
    software: "Zenoti",
    status: "Completed",
    remarks: "Wants to onboard ASAP. F",
  },
  {
    ids: "VIS-00",
    salonname: "Luxe Locks Studio",
    date: "15/07/2024 ",
    seat: "5-7",
    manage: 2,
    grow: 4,
    promote: 4,
    overall: 4,
    software: "Fresha",
    status: "Planned",
    remarks: "Interested in collaboration, requested service details.",
  },
  {
    ids: "CL-V001",
    salonname: "Élan Salon & Spa",
    date: "16/07/2024 ",
    seat: "5-7",
    manage: 1,
    grow: 5,
    promote: 2,
    overall: 2,
    software: "Vagaro",
    status: "Expired",
    remarks: "Highly potential partner, located in a prime area.",
  },
  {
    ids: "SVST-025",
    salonname: "Divine Glow Stud..",
    date: "18 /07/2024 ",
    seat: "5-7",
    manage: 3,
    grow: 2,
    promote: 4,
    overall: 2,
    software: "Booksy",
    status: "Completed",
    remarks: "Not very responsive, follow up next week.",
  },
  {
    ids: "VISIT-09999",
    salonname: "Glamistry Salon",
    date: "14/07/2024 ",
    seat: "5-7",
    manage: 2,
    grow: 3,
    promote: 3,
    overall: 3,
    software: "Zenoti",
    status: "Completed",
    remarks: "Wants to onboard ASAP. F",
  },
];
export const settingData = [
  {
    icon: <TerritoryDetailsIcon />,
    path: "/setting/territory-details",
    title: "Territory Details",
    text: "View performance Metrics and PIN - wise salon distributions",
  },
  {
    icon: <BAProfilesIcon />,
    title: "BA Profiles",
    path: "/setting/ba-profiles",
    text: "View and manage Business Associate Infirmations",
  },
  {
    icon: <BankdetailsIcon />,
    title: "Bank details",
    path: "/setting/bank-details",
    text: "Add or update bank account details for payout",
  },
  {
    icon: <EarningIcon />,
    title: "Earning",
    path: "/setting/earning/platform",
    text: "Track revenue generated and view commission breakdowns",
  },
];
export const totalPincodeData = [
  {
    title: "Registered vs Assigned",
    icon: <AppointmentIcon />,
    value: "90 / 270",
    change: "+9",
    percent: "+12%",
  },
  {
    title: "Active  vs Registered",
    icon: <ActivecheckIcon />,
    value: "21 / 90",
    change: "+2",
    percent: "+8%",
  },
  {
    title: "Territory Sales",
    icon: <DollerIcon />,
    value: "₹1,26,240",
    vs: "VS LAST MONTH",
    change: "+2",
    percent: "+8%",
  },
];

export const memberformData = [
  {
    pin: 234567,
    city: "Pune/Maharashtra",
    ProspectPartner: 30,
    RegisteredPartner: 40,
    ActivePartner: 35,
    HealthScore: 35,
    issue: [{ val: 2 }, { val: 3 }],
    TotalSales: "₹24,600",
    remarks: "Pangri",
  },
  {
    pin: 431007,
    city: "Aurangabad/Maharashtra",
    ProspectPartner: 25,
    RegisteredPartner: 50,
    ActivePartner: 40,
    HealthScore: 25,
    issue: [{ val: 2 }, { val: 3 }],
    TotalSales: "₹30,800",
    remarks: "Cidco N-6",
  },
  {
    pin: 234567,
    city: "Pune/Maharashtra",
    ProspectPartner: 30,
    RegisteredPartner: 40,
    ActivePartner: 35,
    HealthScore: 35,
    issue: [{ val: 2 }, { val: 3 }],
    TotalSales: "₹24,600",
    remarks: "Pangri",
  },
  {
    pin: 144205,
    city: "Phagwara/Punjab",
    ProspectPartner: 15,
    RegisteredPartner: 45,
    ActivePartner: 38,
    HealthScore: 40,
    issue: [{ val: 2 }, { val: 3 }],
    TotalSales: "₹35,600",
    remarks: "Lakhpur",
  },
  {
    pin: 384002,
    city: "Mehsana/Gujarat",
    ProspectPartner: 20,
    RegisteredPartner: 38,
    ActivePartner: 30,
    HealthScore: 32,
    issue: [{ val: 2 }, { val: 3 }],
    TotalSales: "₹28,600",
    remarks: "Palavasna",
  },
];

export const BankDetailsData = [
  {
    name: "Aarav Sharma",
    gender: "Male",
    avatar: "/assets/png/aarav-sharma.png",
    bank: "HDFC Bank",
    accountNo: "XXXX XXXX 5423",
    ifsc: "HDFC0001234",
    addedOn: "02 June 2025",
    status: "Verified",
  },
  {
    name: "Ramesh Patel",
    gender: "Male",
    avatar: "/assets/png/ramesh-patel.png",
    bank: "ICICI Bank",
    accountNo: "XXXX XXXX 9123",
    ifsc: "ICIC0003321",
    addedOn: "02 June 2025",
    status: "Pending",
  },
  {
    name: "Priya Sharma",
    gender: "Female",
    avatar: "/assets/png/priya-sharma.png",
    bank: "ICICI Bank",
    accountNo: "XXXX XXXX 4125",
    ifsc: "AXIS0000945",
    addedOn: "02 June 2025",
    status: "Rejected",
  },
];

export const PlatformEarningData = [
  {
    RevenueType: "Subscription",
    Count: 18,
    Revenue: "₹25,000  ",
    RevenueGrowth: "88 %",
  },
  {
    RevenueType: "Get Featured",
    Count: 12,
    Revenue: "₹30,000  ",
    RevenueGrowth: "90 %",
  },
  {
    RevenueType: "Ads Manager",
    Count: 10,
    Revenue: "₹35,000  ",
    RevenueGrowth: "92 %",
  },
  {
    RevenueType: "Total",
    Count: 40,
    Revenue: "₹90,000  ",
    RevenueGrowth: "96 %",
  },
];

export const EarningDetailsData = [
  {
    image: "/assets/png/ramesh-patel.png",
    name: "Esther Howard",
    TerritoryName: "Western Crest",
    TotalEarning: "₹1,70,000",
    TotalAmount: "₹75,500",
    TransactionID: "TXN8745KLM932",
    Remarks: "Earnings have shown consistent month-on-month growth.",
    File: <FileIcon />,
  },
  {
    image: "/assets/png/ramesh-patel.png",
    name: "Guy Hawkins",
    TerritoryName: "Western Crest",
    TotalEarning: "₹1,25,000",
    TotalAmount: "₹89,999",
    TransactionID: "TRX202506140934",
    Remarks: "Top-performing location in its cluster.",
    File: <FileIcon />,
  },
  {
    image: "/assets/png/ramesh-patel.png",
    name: "Esther Howard",
    TerritoryName: "Western Crest",
    TotalEarning: "₹1,75,500",
    TotalAmount: "₹60,000",
    TransactionID: "TXN-AHND-502398",
    Remarks: "Increased footfall led to better earnings this week.",
    File: <FileIcon />,
  },
  {
    image: "/assets/png/ramesh-patel.png",
    name: "Esther Howard",
    TerritoryName: "Western Crest",
    TotalEarning: "₹1,70,000",
    TotalAmount: "₹75,500",
    TransactionID: "TXN8745KLM932",
    Remarks: "Earnings have shown consistent month-on-month growth.",
    File: <FileIcon />,
  },
  {
    image: "/assets/png/ramesh-patel.png",
    name: "Guy Hawkins",
    TerritoryName: "Western Crest",
    TotalEarning: "₹1,25,000",
    TotalAmount: "₹76,500",
    TransactionID: "TRX202506140934",
    Remarks: "Top-performing location in its cluster.",
    File: <FileIcon />,
  },
];
export const ServiceData = [
  { name: "Mon", value: 40000 },
  { name: "Tue", value: 28000 },
  { name: "Wed", value: 48000 },
  { name: "Thu", value: 33000 },
  { name: "Fri", value: 20000 },
  { name: "Sat", value: 25000 },
  { name: "sun", value: 42000 },
];
export const PackageData = [
  { name: "Mon", value: 33300 },
  { name: "Tue", value: 19000 },
  { name: "Wed", value: 45000 },
  { name: "Thu", value: 27000 },
  { name: "Fri", value: 32000 },
  { name: "Sat", value: 49000 },
  { name: "sun", value: 12000 },
];
export const ProductData = [
  { name: "Mon", value: 31000 },
  { name: "Tue", value: 14000 },
  { name: "Wed", value: 28000 },
  { name: "Thu", value: 48000 },
  { name: "Fri", value: 37000 },
  { name: "Sat", value: 20000 },
  { name: "sun", value: 43000 },
];
export const VoucherData = [
  { name: "Mon", value: 26000 },
  { name: "Tue", value: 36000 },
  { name: "Wed", value: 47000 },
  { name: "Thu", value: 32000 },
  { name: "Fri", value: 19000 },
  { name: "Sat", value: 27000 },
  { name: "sun", value: 12000 },
];
export const MembershipData = [
  { name: "Mon", value: 26000 },
  { name: "Tue", value: 13000 },
  { name: "Wed", value: 29000 },
  { name: "Thu", value: 47000 },
  { name: "Fri", value: 19000 },
  { name: "Sat", value: 27000 },
  { name: "sun", value: 12000 },
];
export const GiftCardData = [
  { name: "Mon", value: 34000 },
  { name: "Tue", value: 19000 },
  { name: "Wed", value: 42000 },
  { name: "Thu", value: 11000 },
  { name: "Fri", value: 31000 },
  { name: "Sat", value: 48000 },
  { name: "sun", value: 38000 },
];
export const Top10ServicesData = [
  { name: "Hair Spa", value: 8.8 },
  { name: "Hair Color", value: 7.0 },
  { name: "Cutting", value: 5.0 },
  { name: "Face Wash", value: 3.8 },
  { name: "Nail art", value: 9.4 },
  { name: "Blow out", value: 6.6 },
  { name: "Manicure", value: 8.8 },
  { name: "Keratin", value: 7.8 },
  { name: "Waxing", value: 4.7 },
  { name: "Threading", value: 3.0 },
];
export const TopSellingProductsData = [
  { name: "Skin Care", value: 9.4 },
  { name: "Makeup", value: 4.4 },
  { name: "Masks", value: 7.0 },
  { name: "Aloe Vera", value: 6.3 },
  { name: "Retional", value: 9.8 },
  { name: "Perfumes", value: 3.0 },
  { name: "Scrubs", value: 3.9 },
  { name: "Lakme", value: 6.0 },
  { name: "Clinique", value: 8.8 },
  { name: "Fragrances", value: 7.1 },
];

export const statusSummaryData = [
  { label: "New", count: 20, color: "#FFEFDB", border: "#F58400" },
  { label: "Confirmed", count: 13, color: "#FFF", border: "#8EBAF6" },
  { label: "Completed", count: 21, color: "#E3F7E9", border: "#31A553" },
  { label: "Expired", count: 15, color: "#FFFF", border: "#A855F7" },
  { label: "No Show", count: 19, color: "#FFF", border: "#B3B3B3" },
  { label: "Canceled", count: 24, color: "#F13737", border: "#E51010" },
];
export const filtersData = [
  { label: "Select TC", options: ["TC 1", "TC 2", "TC 3"] },
  { label: "Select RM", options: ["RM 1", "RM 2"] },
  { label: "Select FE", options: ["FE 1", "FE 2"] },
  { label: "Select Status", options: ["New", "Confirmed", "Completed"] },
  { label: "Select Booking", options: ["Today", "Upcoming", "Past"] },
];
