import {
  ActivecheckIcon,
  AdsNotIcon,
  AppoIcon,
  AppointmentIcon,
  AttentionSquareIcon,
  BankLinkIcon,
  CalenderIcon,
  CatalogIncompleteIcon,
  ConfigureOfferIncompleteIcon,
  CreativeIcon,
  CreditCardIcon,
  DashbordIcon,
  DateTimeIcon,
  DigitalIcon,
  GetFeatIcon,
  GetFeaturedIcon,
  MessgeIcon,
  MsgCenterIcon,
  NewClientIcon,
  NextPageIcon,
  NoappointIcon,
  NoEasyShareIcon,
  NoPartnerIcon,
  NoPromoCodeIcon,
  NosaleIcon,
  OnboardingIcon,
  PatnershipIcon,
  PhoneLinkIcon,
  ProductNotAddedIcon,
  PromoCodeIcon,
  ReportIcon,
  ReviewIcon,
  RoundmodeltrainingIcon,
  SaleParcentIcon,
  SalesIcon,
  SalessIcon,
  SearchIcon,
  SelectdragIcon,
  SettingIcon,
  StarIcon,
  TeamIcon,
  TeamsIcon,
  VectorIcon,
  GoodIcon,
  BadIcon,
  ViewIcon,
  ViewReportIcon,
  AddVisitIcon,
  AddFollowUpIcon,
  AssignPartnerIcon,
  LastVisitSummaryIcon,
  SubmitIcon,
  SetupIcon,
  ClientEngagementIcon,
  PromoteUsageIcon,
  OfferIcon,
  CatalogStaffIcon,
  ProfileIcon,
  ManageIcon,
  GroIcon,
  GrowIcon,
  OutcomeIcon,
  PromotoIcon,
  PlusIcon,
} from "./Icon";
import { BedIcon } from "lucide-react";

export const navItemsData = [
  { id: 1, name: "Dashboard", icon: <DashbordIcon />, path: "/dashboard" },
  {
    id: 2,
    name: "Planner",
    icon: <CalenderIcon />,
    path: "/",
  },
  { id: 3, name: "Insights", icon: <SearchIcon />, path: "/insights" },
  { id: 4, name: "Partner", icon: <PatnershipIcon />, path: "/partner" },
  { id: 5, name: "sales", icon: <SalessIcon />, path: "/" },
  { id: 6, name: "Team", icon: <TeamsIcon />, path: "/" },
  { id: 7, name: "Report", icon: <ReportIcon />, path: "/" },
  {
    id: 8,
    name: "Training",
    icon: <RoundmodeltrainingIcon />,
    path: "/deshbord",
  },
  { id: 9, name: "setting", icon: <SettingIcon />, path: "/deshbord" },
];
export const statsData = [
  {
    title: "Registered vs Assigned",
    icon: <AppointmentIcon />,
    value: "90 / 270",
    change: "+9",
    percent: "+12%",
  },
  {
    title: "Active  vs Registered",
    icon: <ActivecheckIcon />,
    value: "21 / 90",
    change: "+2",
    percent: "+8%",
  },
  {
    title: "Visits this month",
    icon: <NextPageIcon />,
    value: "50 / 250",
    change: "+2",
    percent: "+8%",
  },
  {
    title: "Sales",
    icon: <SaleParcentIcon />,
    value: "150 / 100",
    change: "+9",
    percent: "+6%",
  },
  {
    title: "Appointment",
    icon: <VectorIcon />,
    value: "75 / 100",
    change: "+9",
    percent: "+2%",
  },
  {
    title: "Needs attention",

    icon: <AttentionSquareIcon />,
    value: "15 / 21",
    change: "+2",
    percent: "+2%",
  },
];
export const initialData = [
  {
    id: 1,
    icon: <OnboardingIcon />,
    title: "Onboarding",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 2,
    icon: <SalesIcon />,
    title: "Sales",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 3,
    icon: <PromoCodeIcon />,
    title: "Promo Code",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 4,
    icon: <DigitalIcon />,
    title: "Digital Ads",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 5,
    icon: <StarIcon />,
    title: "Easy Share",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 6,
    icon: <AppoIcon />,
    title: "Appointment",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 7,
    icon: <MessgeIcon />,
    title: "Campaign Message",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 8,
    icon: <GetFeaturedIcon />,
    title: "Get Featured",
    value: 0,
    total: 20,
    change: 0,
  },
  {
    id: 9,
    icon: <SelectdragIcon />,
    title: "Creative Studio",
    value: 0,
    total: 20,
    change: 20,
  },
  {
    id: 10,
    icon: <ReviewIcon />,
    title: "Review",
    value: 0,
    total: 20,
    change: 0,
  },
];
export const healthData = [
  { id: 1, title: "Catalog & Staff", value: 92, score: 9.2 },
  { id: 2, title: "Offers", value: 75, score: 7.5 },
  { id: 3, title: "Client Engagement", value: 42, score: 4.2 },
  { id: 4, title: "Promote Usage", value: 84, score: 8.4 },
  { id: 5, title: "Venue Setup", value: 25, score: 2.5 },
];

export const chartdata = [
  { month: "Jan", registered: 1500, active: 200 },
  { month: "Feb", registered: 1400, active: 600 },
  { month: "Mar", registered: 1800, active: 400 },
  { month: "Apr", registered: 2300, active: 300 },
  { month: "May", registered: 1900, active: 800 },
  { month: "Jun", registered: 2000, active: 1500 },
  { month: "Jul", registered: 2100, active: 1400 },
  { month: "Aug", registered: 1700, active: 1200 },
  { month: "Sep", registered: 1200, active: 1600 },
  { month: "Oct", registered: 1400, active: 1500 },
  { month: "Nov", registered: 1000, active: 700 },
  { month: "Dec", registered: 900, active: 850 },
];
export const tasksData = [
  {
    id: 1,
    title: "Incomplete Onboarding",
    subtitle: "14 Salons",
    icon: <CreditCardIcon />,
  },
  {
    id: 2,
    title: "Off-Peak hours not set",
    subtitle: "8 Salons",
    icon: <NewClientIcon />,
  },
  {
    id: 3,
    title: "Bank account not linked",
    subtitle: "10 Salons",
    icon: <BankLinkIcon />,
  },
  {
    id: 4,
    title: "No monthly target set",
    subtitle: "11 Salons",
    icon: <PhoneLinkIcon />,
  },
  {
    id: 5,
    title: "Staff not added / incomplete",
    subtitle: "13 Salons",
    icon: <TeamIcon />,
  },
  {
    id: 6,
    title: "Subscription Overdue",
    subtitle: "5 Salons",
    icon: <DateTimeIcon />,
  },
];
export const GrowthtasksData = [
  {
    id: 1,
    title: "No Sale (7days)",
    subtitle: "28 salons",
    icon: <NosaleIcon />,
  },
  {
    id: 2,
    title: "No Easy Share (30 days)",
    subtitle: "28 salons",
    icon: <NoEasyShareIcon />,
  },
  {
    id: 3,
    title: "No Appointment(7 days)",
    subtitle: "17 salons",
    icon: <NoappointIcon />,
  },
  {
    id: 4,
    title: "Creative not used (30 d)",
    subtitle: "17 salons",
    icon: <CreativeIcon />,
  },
  {
    id: 5,
    title: "Catalog Incomplete",
    subtitle: "13 salons",
    icon: <CatalogIncompleteIcon />,
  },
  {
    id: 6,
    title: "Ads not used (60 days)",
    subtitle: "5 Salons",
    icon: <AdsNotIcon />,
  },
  {
    id: 7,
    title: "Configure Offer Incomplete",
    subtitle: "21 Salons",
    icon: <ConfigureOfferIncompleteIcon />,
  },
  {
    id: 8,
    title: "Msg Center not used (30 d)",
    subtitle: "21 Salons",
    icon: <MsgCenterIcon />,
  },
  {
    id: 9,
    title: "No Promo code (60 days )",
    subtitle: "21 salons",
    icon: <NoPromoCodeIcon />,
  },
  {
    id: 10,
    title: "Get Feat. not used (60 days)",
    subtitle: "21 Salons",
    icon: <GetFeatIcon />,
  },
  {
    id: 11,
    title: "Product not added ",
    subtitle: "21 Salons",
    icon: <ProductNotAddedIcon />,
  },
  {
    id: 12,
    title: "Partner not visited (30 days)",
    subtitle: "21 Salons",
    icon: <NoPartnerIcon />,
  },
];
export const CriticalTaskData = [
  {
    id: 1,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Chroma Lounge",
    address: "281 Madison Street,SoHo Dis...",
    health: 30,
    issue: [{ val: 2 }, { val: 3 }],
    staff: 10,
    onboarding: <GoodIcon />,
    bankacc: <GoodIcon />,
    monthlytarget: <BadIcon />,
    subscription: "Active",
    lastvisit: "3 days ago",
    nextvisit: "July 10, 2025",
    tcname: "Ayesha Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 2,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Maison Glow",
    address: "Luxe Layers Lounge, 1285",
    health: 12,
    issue: [{ val: 3 }, { val: 1 }],
    staff: 5,
    onboarding: <BadIcon />,
    bankacc: <BadIcon />,
    monthlytarget: <GoodIcon />,
    subscription: "Due",
    lastvisit: "11 days ago",
    nextvisit: "Aug 10, 2025",
    tcname: "Meera Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 2,
    img: "/assets/png/Chroma-Lounge.png",
    name: "The Gilded Comb",
    address: "The Styling Suite, 45 Ke....",
    health: 25,
    issue: [{ val: 3 }, { val: 2 }],
    staff: 3,
    onboarding: <GoodIcon />,
    bankacc: <GoodIcon />,
    monthlytarget: <GoodIcon />,
    subscription: "Expired",
    lastvisit: "6 days ago",
    nextvisit: "july 10, 2025",
    tcname: "Ritika Varma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 4,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Luxe Layers",
    address: "Glow Theory Studio, 722...",
    health: 40,
    issue: [{ val: 2 }, { val: 3 }],
    staff: 6,
    onboarding: <GoodIcon />,
    bankacc: <GoodIcon />,
    monthlytarget: <BadIcon />,
    subscription: "Active",
    lastvisit: "3 days ago",
    nextvisit: "July 10, 2025",
    tcname: "Ayesha Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 5,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Opal & Shine",
    address: "Luxe Layers Lounge, 1285",
    health: 12,
    issue: [{ val: 3 }, { val: 1 }],
    staff: 5,
    onboarding: <BadIcon />,
    bankacc: <BadIcon />,
    monthlytarget: <GoodIcon />,
    subscription: "Due",
    lastvisit: "11 days ago",
    nextvisit: "Aug 10, 2025",
    tcname: "Meera Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
  {
    id: 6,
    img: "/assets/png/Chroma-Lounge.png",
    name: "The Hair Bar",
    address: "Blush & Beam Salon, Unit 5..",
    health: 15,
    issue: [{ val: 1 }, { val: 2 }],
    staff: 5,
    onboarding: <BadIcon />,
    bankacc: <BadIcon />,
    monthlytarget: <GoodIcon />,
    subscription: "Expired",
    lastvisit: "6 days ago",
    nextvisit: "july 10, 2025",
    tcname: "Ritika Varma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    action: "...",
  },
];
export const ManageData = [
  { label: "Manage: 3", color: "!text-[#F13737]" },
  { label: "Grow: 2", color: "!text-[#F58400]" },
  { label: "Promote: 4", color: "!text-[#5B14D1]" },
  { label: "Overall: 2", color: "!text-[#31A553]" },
];
export const textsData = [
  { label: "Critical : 6 ", color: "!text-[#F13737]" },
  { label: "Growth : 4", color: "text-green-400" },
  { label: "Health : 8", color: "!text-[#5d14d1d7]" },
];

export const contactsData = [
  {
    role: "Owner :",
    name: "John Walley",
    number: "23246-93902",
  },
  {
    role: "Manager :",
    name: "Esther Howard",
    number: "78363-47438",
  },
];

export const fermtcData = [
  {
    role: "FE :",
    name: "Aditi Singh",
    number: "32456-39432",
  },
  {
    role: "RM :",
    name: "Rohit Sharma",
    number: "23348-32948",
  },
  {
    role: "TC :",
    name: "Priya Kumari",
    number: "84950-34859",
  },
];
export const issuesData = {
  critical: [
    { title: "Incomplete Onboarding", days: "30 days" },
    { title: "Off-Peak hours not set", days: "15 days" },
    { title: "Missing Bank Account", days: "20 days" },
    { title: "Subscription overdue", days: "10 days" },
  ],
  growth: [
    { title: "Website not optimized", days: "12 days" },
    { title: "Low engagement on campaigns", days: "8 days" },
  ],
};
export const issues1Data = {
  manage: [
    { title: "Appointment Management", days: "2/5" },
    { title: "Catalog Management", days: "3/5" },
    { title: "Client Management", days: "4/5" },
    { title: "Staff Management", days: "1/5" },
  ],
  growth: [
    { title: "Client Management", days: "4/5" },
    { title: "Staff Management", days: "1/5" },
    { title: "Appointment Management", days: "2/5" },
    { title: "Catalog Management", days: "3/5" },
  ],
  promote: [
    { title: "Staff Management", days: "1/5" },
    { title: "Appointment Management", days: "2/5" },
    { title: "Catalog Management", days: "3/5" },
    { title: "Client Management", days: "4/5" },
  ],
};
export const reportsData = [
  {
    type: "Visit on",
    date: "April 10th, 2024",
    score: "30/50",
    remarks:
      "Showed keen interest in CRM and membership features. Demo scheduled.",
  },
  {
    type: "Follow Up on",
    date: "April 10th, 2024",
    reason: "Task from previous visit not completed",
    remarks:
      "Showed keen interest in CRM and membership features. Demo scheduled.",
  },
  {
    type: "Visit on",
    date: " April 10th, 2024",
    score: "30/50",
    remarks:
      "Showed keen interest in CRM and membership features. Demo scheduled.",
  },
];

// helperData.js
export const stepsData = [
  {
    type: "info",
    fields: [
      { label: "Name", value: "Raman" },
      { label: "Address", value: "Delhi" },
      { label: "Email", value: "raman@example.com" },
    ],
  },
  {
    type: "question",
    question: "Bot Question 1: How are you today?",
    placeholder: "Your answer",
  },
  {
    type: "question",
    question: "Bot Question 2: What is your favorite color?",
    placeholder: "Your answer",
  },
];

export const namesData = [
  "Sanya Desai",
  "Tanya Sethi",
  "Priya Nair",
  "Meera Sharma",
  "Ishita Bose",
];
export const nameData = [
  "Neha Reddy",
  "Neha Singh",
  "Tanya Sethi",
  "Sanya Desai",
];
export const nametcData = [
  "Sanya Desai",
  "Neha Singh",
  "Kavita Menon",
  "Ritika Verma",
  "Meera Sharma",
];
export const namemrData = [
  "Divya Malhotra",
  "manish Vrema",
  "Rhea Malhotra",
  "Neha Singh",
];
export const namemrfeData = [
  "Ayesha Sharma",
  "Ishita Bose",
  "Rhea Malhotra",
  "Neha Singh",
];

export const reasonData = [
  "Critical Task",
  "CataLog & Offers",
  "Appointment &  Sales",
  "Promote & Marketing",
  "Techanical Issues",
  "Others",
];
export const menuItemsData = [
  { id: 1, label: "View as partner", icon: <ViewIcon />, path: "/new-visit" },
  {
    id: 2,
    label: "View Report",
    icon: <ViewReportIcon />,
    path: "/insights/NewVisit",
  },
  { id: 3, label: "Add Visit", icon: <AddVisitIcon />, path: "/new-visit" },
  {
    id: 4,
    label: "Add Follow Up",
    icon: <AddFollowUpIcon />,
    path: "/new-visit",
  },
  {
    id: 5,
    label: "Add Visit Report",
    icon: <AddVisitIcon />,
    path: "/NewVisit",
  },
  {
    id: 6,
    label: "Assign Partner",
    icon: <AssignPartnerIcon />,
    path: "/",
  },
];
export const menuItemstab2Data = [
  {
    id: 1,
    label: "View Report",
    icon: <ViewReportIcon />,
    path: "/insights/NewVisit",
  },
  { id: 2, label: "Add Visit", icon: <AddVisitIcon />, path: "/new-visit" },
  {
    id: 3,
    label: "Add Follow Up",
    icon: <AddFollowUpIcon />,
    path: "/new-visit",
  },
  {
    id: 4,
    label: "Add Visit Report",
    icon: <PlusIcon />,
    path: "/NewVisit",
  },
  {
    id: 5,
    label: "Assign Partner",
    icon: <AssignPartnerIcon />,
    path: "/",
  },
];
export const fromsummitData = [
  { icon: <LastVisitSummaryIcon />, label: "Last Visit Summary" },
  { icon: <CatalogStaffIcon />, label: "Catalog & Staff" },
  { icon: <OfferIcon />, label: "Offers" },
  { icon: <PromoteUsageIcon />, label: "Promote Usage" },
  { icon: <ClientEngagementIcon />, label: "Client Engagement" },
  { icon: <SetupIcon />, label: "Set up" },
  { icon: <SubmitIcon />, label: "Submit" },
];
export const ProfileManageData = [
  { icon: <ProfileIcon />, label: "Profile" },
  { icon: <ManageIcon />, label: "Manage" },
  { icon: <GrowIcon />, label: "Grow" },
  { icon: <PromotoIcon />, label: "Promote" },
  { icon: <OutcomeIcon />, label: "Outcome" },
];

export const data = [
  {
    category: "Venue Setup",
    score: "9/10",
    remarks:
      "All complete, missing cancellation policy. Could add more amenities.",
  },
  {
    category: "Catalog & Staff",
    score: "8/10",
    remarks:
      "Services added, 1 inactive staff still listed. Staff profiles need updating.",
  },
  {
    category: "Offers",
    score: "6/10",
    remarks:
      "Gift card & promo active, no membership setup yet. Explore loyalty programs.",
  },
  {
    category: "Promote Usage",
    score: "5/10",
    remarks:
      "Not yet using Get Featured or Campaign Msg. Easy Share links created but low clicks. ",
  },
];
export const Metricdata = [
  {
    Metric: "Services (Count)",
    last: "50 services",
    Current: "40 services",
  },
  {
    Metric: "Package (Count)",
    last: "10 Packages",
    Current: "14 Packages",
  },
  {
    Metric: "Book-a-Look (Count)",
    last: "5 looks",
    Current: "8 looks",
  },
  {
    Metric: "Product (Count)",
    last: "5 looks",
    Current: "22 Products",
  },
  {
    Metric: "Staff (Count)",
    last: "5 staff",
    Current: "3 staff",
  },
];
export const offerdata = [
  {
    Metric: "Voucher (Count)",
    last: "100 vouchers",
    Current: "90 vouchers",
  },
  {
    Metric: "Membership (Count)",
    last: "2 Plans",
    Current: "4 Plans",
  },
  {
    Metric: "Promo code (Count)",
    last: "50 Codes",
    Current: "70 Codes",
  },
  {
    Metric: "Gift Card (Count)",
    last: "10 Cards",
    Current: "12 Cards",
  },
];

export const PromoteUsagedata = [
  {
    Metric: "Get Featured (No. of Days)",
    last: "7 days",
    Current: "8 days",
  },
  {
    Metric: "Easy Share (No. of Links)",
    last: "7 days",
    Current: "6 days",
  },
  {
    Metric: "Easy Share (Clicks)",
    last: "500 clicks",
    Current: "510 clicks",
  },
  {
    Metric: "Creative St. (No. of Temp.)",
    last: "10 templates",
    Current: "12 templates",
  },
  {
    Metric: "Ad Manager (No. of Days)",
    last: "10 templates",
    Current: "9 templates",
  },
  {
    Metric: "Campaign Msg Sent (Count)",
    last: "1000 msgs",
    Current: "1002 msgs",
  },
];

export const ClientEngagementdata = [
  {
    Metric: "Appointment  Received ",
    last: "150",
    Current: "140",
  },
  {
    Metric: "Appointment  Complete ",
    last: "140",
    Current: "146",
  },
  {
    Metric: "Repeat Clients Visit ",
    last: "80",
    Current: "510",
  },
  {
    Metric: "New Client Add ",
    last: "60",
    Current: "62",
  },
  {
    Metric: "Total Client",
    last: "500",
    Current: "400",
  },
  {
    Metric: "Review Received ",
    last: "20",
    Current: "30",
  },
  {
    Metric: "Review Received ",
    last: "30",
    Current: "40",
  },
  {
    Metric: "Sales",
    last: "₹50,000",
    Current: "₹45,000",
  },
];
export const Setupdata = [
  {
    Metric: "Business Name and Logo",
    last: "Yes",
    Current: "Yes",
  },
  {
    Metric: "Complete Add. and Location Pin Set",
    last: "Yes",
    Current: "No",
  },
  {
    Metric: "About (Description)",
    last: "Yes",
    Current: "Yes",
  },
  {
    Metric: "Off Peak Hours",
    last: "No",
    Current: "Yes",
  },
  {
    Metric: "Contact Number verified",
    last: "Yes",
    Current: "Yes",
  },
  {
    Metric: "Social Media Links",
    last: "Yes",
    Current: "No",
  },
  {
    Metric: "Bank Account",
    last: "No",
    Current: "Yes",
  },
  {
    Metric: "Compliance - Staff  'Curr. Employed'",
    last: "Yes",
    Current: "Yes",
  },
];
export const timesData = [
  "01:00 PM",
  "02:00 PM",
  "03:00 PM",
  "04:00 PM",
  "05:00 PM",
  "06:00 PM",
  "07:00 PM",
  "08:00 PM",
  "09:00 PM",
  "10:00 PM",
  "12:00 PM",
  "01:00 AM",
  "02:00 AM",
  "03:00 AM",
  "04:00 AM",
  "05:00 AM",
  "06:00 AM",
  "07:00 AM",
  "08:00 AM",
  "09:00 AM",
  "10:00 AM",
  "11:00 AM",
  "12:00 AM",
];

export const salonSizesData = [
  { id: "size-1", value: "0-3", label: "0 - 3 seats" },
  { id: "size-2", value: "4-7", label: "4 - 7 seats" },
  { id: "size-3", value: "8-12", label: "8 - 12 seats" },
  { id: "size-4", value: "16+", label: "16 & above" },
];

export const ratingLabelsData = [
  "Rate the following from 1 - 5 ",
  "1 - not needed",
  "2 - not sure",
  "3 - needed but not immediately",
  "4 - needed",
  "5 - strongly needed",
];

export const GrowthTaskData = [
  {
    id: 1,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Chroma Lounge",
    address: "281 Madison Street,SoHo Dis...",
    health: 30,
    issue: [{ val: 2 }, { val: 3 }],
    saleid: "₹12,500",
    Appt: "5",
    Catalog: "20/3",
    Promocode: "0",
    Getfeat: "0",
    EasyShare: "10/2",
    CreativeStudio: "0",
    Admanager: "0",
    CompMsg: "0",
    NextVisit: "July 14,2025",
    tcname: "Ayesha Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
  },
  {
    id: 2,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Maison Glow",
    address: "Luxe Layers Lounge, 1285",
    health: 12,
    issue: [{ val: 3 }, { val: 2 }],
    saleid: "₹15,000",
    Appt: "10",
    Catalog: "20/3",
    Promocode: "2",
    Getfeat: "2",
    EasyShare: "10/4",
    CreativeStudio: "2",
    Admanager: "3",
    CompMsg: "20",
    NextVisit: "Aug 10 ,2025",
    tcname: "Meera Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
  },
  {
    id: 3,
    img: "/assets/png/Chroma-Lounge.png",
    name: "The Gilded Comb",
    address: "The Styling Suite, 45 Ke....",
    health: 25,
    issue: [{ val: 1 }, { val: 3 }],
    saleid: "₹18,750",
    Appt: "6",
    Catalog: "20/3",
    Promocode: "5",
    Getfeat: "4",
    EasyShare: "20/3",
    CreativeStudio: "4",
    Admanager: "5",
    CompMsg: "15",
    NextVisit: "July 14,2025",
    tcname: "Ritika Varma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
  },
  {
    id: 4,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Luxe Layers",
    address: "Blush & Beam Salon, Unit 5...",
    health: 16,
    issue: [{ val: 3 }, { val: 4 }],
    saleid: "₹20,000",
    Appt: "8",
    Catalog: "20/3",
    Promocode: "5",
    Getfeat: "5",
    EasyShare: "12/4",
    CreativeStudio: "6",
    Admanager: "8",
    CompMsg: "12",
    NextVisit: "sep 11,2025",
    tcname: "Tanya Sethi",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
  },
  {
    id: 5,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Opal & Shine",
    address: "Radiance Hair Studio, 3rd f..",
    health: 35,
    issue: [{ val: 4 }, { val: 3 }],
    saleid: "₹23,400",
    Appt: "12",
    Catalog: "20/3",
    Promocode: "5",
    Getfeat: "5",
    EasyShare: "12/4",
    CreativeStudio: "6",
    Admanager: "8",
    CompMsg: "12",
    NextVisit: "July 10,2025",
    tcname: "Kavita Menon",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
  },
];

export const RegisteredPartnerData = [
  {
    id: 1,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Chroma Lounge",
    city: "MG Road, Banglore",
    health: 45,
    issue: [{ val: 2 }, { val: 3 }],
    appt: "150",
    sales: "80",
    tcname: "Amitabh Bachan",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    lastVisit: "July 14,2025",
    nextVisit: "July 5,2025",
  },
  {
    id: 2,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Maison Glow",
    city: "Brigade Road, Bangalore",
    health: 40,
    issue: [{ val: 2 }, { val: 3 }],
    appt: "50",
    sales: "80",
    tcname: "-",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    lastVisit: "July 14,2025",
    nextVisit: "-",
  },
  {
    id: 3,
    img: "/assets/png/Chroma-Lounge.png",
    name: "The Gilded Comb",
    city: "Cloud City",
    health: 35,
    issue: [{ val: 2 }, { val: 3 }],
    appt: "₹120",
    sales: "120",
    tcname: "Ayesha Sharma",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    lastVisit: "Jun 01,2025",
    nextVisit: "Apr 10,2025",
  },
  {
    id: 4,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Luxe Layers",
    city: "Treasure Town",
    health: 42,
    issue: [{ val: 2 }, { val: 3 }],
    appt: "₹110",
    sales: "125",
    tcname: "Amitabh Bachan",
    rmname: "-",
    fename: "Vijay Patel",
    lastVisit: "July 14,2025",
    nextVisit: "July 25,2025",
  },
  {
    id: 5,
    img: "/assets/png/Chroma-Lounge.png",
    name: "Opal & Shine",
    city: "Cloud City",
    health: 40,
    issue: [{ val: 2 }, { val: 3 }],
    appt: "₹130",
    sales: "60",
    tcname: "Suresh Mehta",
    rmname: "Rhea Malhotra",
    fename: "Neha Singh",
    lastVisit: "Apr 14,2025",
    nextVisit: "July 5,2025",
  },
];
